IBX-2975: Added API for finding invitations
ibexa/user pull request #41
Opened 2022-06-01 14:23 UTC by ViniTou

| Question      | Answer
| ------------- | ---
| Tickets       |  [IBX-2975](https://issues.ibexa.co/browse/IBX-2975) 
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | yes
| License       | [GPL-2.0](https://github.com/ibexa/admin-ui/blob/main/LICENSE)

#### Checklist:
- [x] Implement tests
- [x] Coding standards (`$ composer fix-cs`)

2022-06-14 08:13 UTC, Nattfarinn approved these changes

2022-06-15 09:37 UTC, alongosz requested changes

2022-06-20 07:20 UTC, Steveb-p requested changes

2022-06-20 07:20 UTC, Steveb-p commented on src/lib/Invitation/Persistence/DoctrineGateway.php
> +        }
```suggestion
        if ($filter === null) {
            $statement = $query->execute();

            return $statement->fetchAllAssociative();
        }

        if ($filter->getRole() !== null) {
            $query->andWhere(
                $query->expr()->eq(
                    't2.role_id',
                    $query->createPositionalParameter($filter->getRole()->id)
                )
            );
        }

        if ($filter->getUserGroup() !== null) {
            $query->andWhere(
                $query->expr()->eq(
                    't2.user_group_id',
                    $query->createPositionalParameter($filter->getUserGroup()->id)
                )
            );
        }

        if ($filter->getIsUsed() !== null) {
            $query->andWhere(
                $query->expr()->eq(
                    't1.used',
                    $query->createPositionalParameter($filter->getIsUsed())
                )
            );
        }
```

2022-06-20 11:41 UTC, alongosz requested changes

2022-06-20 11:41 UTC, alongosz commented on src/contracts/Invitation/InvitationService.php
> +     * @throws \Ibexa\Core\Base\Exceptions\UnauthorizedException
```suggestion
     * @throws \Ibexa\Contracts\Core\Repository\Exceptions\UnauthorizedException
```

2022-06-20 11:41 UTC, alongosz commented on src/contracts/Invitation/InvitationService.php
> +     * @throws \Ibexa\Core\Base\Exceptions\UnauthorizedException
```suggestion
     * @throws \Ibexa\Contracts\Core\Repository\Exceptions\UnauthorizedException
```

2022-06-20 11:41 UTC, alongosz commented on src/lib/Invitation/InvitationService.php
> +     * @throws \Ibexa\Core\Base\Exceptions\UnauthorizedException
```suggestion
     * @throws \Ibexa\Contracts\Core\Repository\Exceptions\UnauthorizedException
```

2022-06-20 11:41 UTC, alongosz commented on src/lib/Invitation/InvitationService.php
> +     * @throws \Ibexa\Core\Base\Exceptions\UnauthorizedException
```suggestion
     * @throws \Ibexa\Contracts\Core\Repository\Exceptions\UnauthorizedException
```

2022-06-23 14:48 UTC, merged