IBX-3070: User thumbnail should not be rendered with border and other minor bugs
ibexa/user pull request #43
Opened 2022-06-22 16:15 UTC by tischsoic

| Question      | Answer
| ------------- | ---
| Tickets       |  https://issues.ibexa.co/browse/IBX-3070
| Bug fix?      | yes/no
| New feature?  | no
| BC breaks?    | no
| Tests pass?   | yes
| Doc needed?   | no
| License       | [GPL-2.0](https://github.com/ibexa/admin-ui/blob/main/LICENSE)

2022-06-23 06:00 UTC, dew326 approved these changes

2022-06-23 06:34 UTC, ViniTou approved these changes

2022-06-23 09:40 UTC, GrabowskiM approved these changes

2022-06-23 12:20 UTC, lucasOsti approved these changes

2022-06-23 12:39 UTC, lucasOsti approved these changes

2022-06-23 12:44 UTC, dew326 approved these changes

2022-06-27 06:33 UTC, ViniTou requested changes

2022-06-27 06:33 UTC, ViniTou commented on src/bundle/Resources/views/profile_image/initials.svg.twig
> +    <text x="50%" y="50%" dominant-baseline="central" text-anchor="middle" font-size="12px" fill="{{ text_color }}">
You still should have fallback to `text` here if `text_color` is not set.

2022-06-27 06:33 UTC, ViniTou commented on src/bundle/Resources/views/profile_image/initials.svg.twig
> +    <ellipse ry="15" rx="15" cy="16" cx="16" fill="{{ background }}" stroke="{{ text_color }}" stroke-width="1" />
Maybe we should not make that same mistake twice and use different variable name for stroke color as it is not text related, right?

2022-06-27 06:46 UTC, ViniTou approved these changes

2022-06-27 06:47 UTC, Nattfarinn approved these changes

2022-06-27 06:50 UTC, Nattfarinn approved these changes

2022-06-27 07:35 UTC, GrabowskiM approved these changes

2022-06-27 08:25 UTC, merged

2022-06-27 08:54 UTC, tischsoic commented
Merged up:
- main: https://github.com/ibexa/user/commit/e3797b2c21d70a5bf2b0a0134e9f40937d2d22f8